from discord_webhook import DiscordWebhook, DiscordEmbed
import time

print("BBBBBBBBBBBBBBBBB   YYYYYYY       YYYYYYY")
print("B::::::::::::::::B  Y:::::Y       Y:::::Y")
print("B::::::BBBBBB:::::B Y:::::Y       Y:::::Y")
print("BB:::::B     B:::::BY::::::Y     Y::::::Y")
print("  B::::B     B:::::BYYY:::::Y   Y:::::YYY")
print("  B::::B     B:::::B   Y:::::Y Y:::::Y  ")
print("  B::::BBBBBB:::::B     Y:::::Y:::::Y   ")
print("  B:::::::::::::BB       Y:::::::::Y     ")
print("  B::::BBBBBB:::::B       Y:::::::Y      ")
print("  B::::B     B:::::B       Y:::::Y       ")
print("  B::::B     B:::::B       Y:::::Y       ")
print("  B::::B     B:::::B       Y:::::Y       ")
print("BB:::::BBBBBB::::::B       Y:::::Y       ")
print("B:::::::::::::::::B     YYYY:::::YYYY    ")
print("B::::::::::::::::B      Y:::::::::::Y    ")
print("BBBBBBBBBBBBBBBBB       YYYYYYYYYYYYY    ")

time.sleep(2)

print("                             __         .__                           _________ __            .___.__              ")
print("  ____ _____    ____ _______/  |_  ____ |  | _____    ____   ____    /   _____//  |_ __ __  __| _/|__| ____  ______")
print("_/ ___\\__  \ _/ __ \\____ \   __\/    \|  | \__  \ _/ __ \ /    \   \_____  \\   __\  |  \/ __ | |  |/  _ \/m  ___/")
print("\  \___ / __ \\  ___/|  |_> >  | |   |  \  |__/ __ \\  ___/|   |  \  /        \|  | |  |  / /_/ | |  (  <_> )___ \ ")
print(" \___  >____  /\___  >   __/|__| |___|  /____(____  /\___  >___|  / /_______  /|__| |____/\____ | |__|\____/____  >")
print("     \/     \/     \/|__|             \/          \/     \/     \/          \/                 \/               \/ ")

time.sleep(1.5)

print("          _______  ______            _______  _______  _        ")
print("|\     /|(  ____ \(  ___ \ |\     /|(  ___  )(  ___  )| \    /\ ")
print("| )   ( || (    \/| (   ) )| )   ( || (   ) || (   ) ||  \  / / ")
print("| | _ | || (__    | (__/ / | (___) || |   | || |   | ||  (_/ /  ")
print("| |( )| ||  __)   |  __ (  |  ___  || |   | || |   | ||   _ (   ")
print("| || || || (      | (  \ \ | (   ) || |   | || |   | ||  ( \ \  ")
print("| () () || (____/\| )___) )| )   ( || (___) || (___) ||  /  \ \ ")
print("(_______)(_______/|/ \___/ |/     \|(_______)(_______)|_/    \/ ")

time.sleep(1)

print("   *                                                   ")
print(" )\))(     (             )  (  (     (       )   ( /(  ")
print("((_)()\   ))\ (   (   ( /(  )\))(   ))\     /((  )\()) ")
print("(_()((_) /((_))\  )\  )(_))((_))\  /((_)   (_))\((_)\  ")
print("|  \/  |(_)) ((_)((_)((_)_  (()(_)(_))     _)((_)/ (_) ")
print("| |\/| |/ -_)(_-<(_-</ _` |/ _` | / -_)    \ V / | |   ")
print("|_|  |_|\___|/__//__/\__,_|\__, | \___|_____\_/  |_|   ")
print("                           |___/      |_____|          ")

url = input ('Enter your Webhook URL:')
message = input ('Enter your message:')

webhook = DiscordWebhook(url=url, content=message)
response = webhook.execute()

time.sleep(0.5)
print("Loading ..")
time.sleep(0.5)
print("Loading.. ")
time.sleep(0.5)
print("Loading ..")
time.sleep(0.5)
print("Loading.. ")
time.sleep(0.5)
print("Loading ..")
time.sleep(0.5)
print("Loading.. ")
time.sleep(0.5)
print("Loading ..")
time.sleep(0.5)
print("Loading.. ")

print("Success!")
print("Your message was send!")

print(message)

print(" ..")
time.sleep(0.5)
print(".. ")
time.sleep(1)
print("This Window will be closed in 10 seconds")

time.sleep(10)
